In [6]:
import numpy as np

In [7]:
def mean_datasets(filenames):
  n = len(filenames)
  if n > 0:
    data = np.loadtxt(filenames[0], delimiter=',')
    for i in range(1,n):
      data += np.loadtxt(filenames[i], delimiter=',')
    
    # Mean across all files:
    data_mean = data/n
     
    return np.round(data_mean, 1)

In [8]:
print(mean_datasets(['data2.csv', 'data3.csv']))

[[12.6  9.4  9.6]
 [10.6  5.  12.1]
 [ 7.   9.4 14.4]
 [ 8.9  3.9  8.7]
 [17.5  9.5  8.8]]
